-- DDLs and loading scripts for the DQ Monitoring framework tables
-- Co-authored with CoCo

-- ============================================================================
-- STEP 4: DATA QUALITY FRAMEWORK CONFIGURATION
-- ============================================================================

-- 4.1 Create DQ Monitoring Schema
CREATE SCHEMA IF NOT EXISTS BANKING_DQ_DB.DQ_MONITORING;

-- ============================================================================
-- 4.2 Create Framework Tables
-- ============================================================================

-- TABLE 1: DQ_RULE_CONFIG - Stores all data quality rules
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (
    RULE_ID VARCHAR(50) NOT NULL,
    RULE_NAME VARCHAR(200) NOT NULL,
    RULE_TYPE VARCHAR(50) NOT NULL,
    FREQUENCY VARCHAR(50) DEFAULT 'ON_DEMAND',
    CRITICALITY VARCHAR(20) NOT NULL,
    DB_NAME VARCHAR(200) NOT NULL,
    TABLE_NM VARCHAR(200) NOT NULL,
    COLUMN_NM VARCHAR(200),
    RULE_DESCRIPTION VARCHAR(1000),
    RULE_SQL VARCHAR(4000) NOT NULL,
    THRESHOLD_VALUE NUMBER(10,2) DEFAULT 0,
    RULE_DIMENSION VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TABLE 2: DQ_RUN_CONTROL - Tracks each execution run
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RUN_CONTROL (
    RUN_ID VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50) NOT NULL,
    RUN_START_TIME TIMESTAMP_NTZ,
    RUN_END_TIME TIMESTAMP_NTZ,
    RULE_EXEC_RESULT VARCHAR(50),
    RULE_OUTPUT_VALUE NUMBER(38,4),
    RUN_STATUS VARCHAR(50),
    TRIGGERED_BY VARCHAR(100),
    ERROR_MESSAGE VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TABLE 3: DQ_RULE_RESULTS - Stores rule-level execution results
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_RESULTS (
    RESULT_ID VARCHAR(50) NOT NULL,
    RUN_ID VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50) NOT NULL,
    DB_NAME VARCHAR(200),
    TABLE_NAME VARCHAR(200),
    COLUMN_NAME VARCHAR(200),
    RULE_NAME VARCHAR(200),
    RULE_TYPE VARCHAR(50),
    EXPECTED_VALUE NUMBER(38,4),
    ACTUAL_VALUE NUMBER(38,4),
    FAILED_RECORD_COUNT NUMBER(38,0),
    TOTAL_RECORD_COUNT NUMBER(38,0),
    PASS_PERCENTAGE NUMBER(10,4),
    RESULT_STATUS VARCHAR(20),
    SEVERITY VARCHAR(20),
    ERROR_SAMPLE_QUERY VARCHAR(4000),
    EXECUTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TABLE 4: DQ_ERROR_RECORDS - Stores detailed failed records
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ERROR_RECORDS (
    ERROR_ID VARCHAR(50) NOT NULL,
    RUN_ID VARCHAR(50) NOT NULL,
    RULE_ID VARCHAR(50) NOT NULL,
    DB_NAME VARCHAR(200),
    TABLE_NAME VARCHAR(200),
    ERROR_RECORD_VARIANT VARIANT,
    ERROR_REASON VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- TABLE 5: DQ_ANOMALY_RESULTS - Stores anomaly detection results
CREATE OR REPLACE TABLE BANKING_DQ_DB.DQ_MONITORING.DQ_ANOMALY_RESULTS (
    ANOMALY_ID VARCHAR(50) NOT NULL,
    RUN_ID VARCHAR(50) NOT NULL,
    DATABASE_NAME VARCHAR(200),
    SCHEMA_NAME VARCHAR(200),
    TABLE_NAME VARCHAR(200),
    METRIC_NAME VARCHAR(200),
    CURRENT_VALUE NUMBER(38,4),
    PREVIOUS_VALUE NUMBER(38,4),
    BASELINE_AVG NUMBER(38,4),
    BASELINE_STDDEV NUMBER(38,4),
    ANOMALY_STATUS VARCHAR(50),
    ANOMALY_REASON VARCHAR(1000),
    DETECTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- 4.3 Load Rules into DQ_RULE_CONFIG
-- ============================================================================

-- BRANCHES rules (6 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'BR-01','Branch ID Uniqueness','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_ID','No duplicate branch IDs','SELECT COUNT(*) - COUNT(DISTINCT BRANCH_ID) FROM BANKING_DQ_DB.RAW.BRANCHES',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'BR-02','Branch ID Not Null','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_ID','PK cannot be null','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE BRANCH_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR-03','Branch Name Not Null','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','BRANCHES','BRANCH_NAME','Every branch must have a name','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE BRANCH_NAME IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'BR-04','IFSC Code Format','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','BRANCHES','IFSC_CODE','Must match ^[A-Z]{4}[0-9]{7}$','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.BRANCHES WHERE IFSC_CODE IS NOT NULL AND NOT IFSC_CODE RLIKE ''^[A-Z]{4}[0-9]{7}$''',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'BR-05','IFSC Code Uniqueness','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','BRANCHES','IFSC_CODE','Each branch has unique IFSC','SELECT COUNT(*) - COUNT(DISTINCT IFSC_CODE) FROM BANKING_DQ_DB.RAW.BRANCHES',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'BR-06','Row Count Check','TECHNICAL','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','BRANCHES',NULL,'Table must have rows','SELECT CASE WHEN COUNT(*) > 0 THEN 0 ELSE 1 END FROM BANKING_DQ_DB.RAW.BRANCHES',0,PARSE_JSON('["completeness"]'),TRUE;

-- CUSTOMERS rules (10 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'CU-01','Customer ID Uniqueness','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','CUSTOMER_ID','No duplicate customer IDs','SELECT COUNT(*) - COUNT(DISTINCT CUSTOMER_ID) FROM BANKING_DQ_DB.RAW.CUSTOMERS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'CU-02','Customer ID Not Null','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','CUSTOMER_ID','PK cannot be null','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE CUSTOMER_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'CU-03','Email Format Valid','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','Must contain @ and valid domain','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE EMAIL IS NOT NULL AND NOT EMAIL RLIKE ''^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$''',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU-04','Email Uniqueness','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','EMAIL','No duplicate emails','SELECT COUNT(*) - COUNT(DISTINCT EMAIL) FROM BANKING_DQ_DB.RAW.CUSTOMERS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'CU-05','Phone Format Valid','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','PHONE','Must be exactly 10 digits','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE PHONE IS NOT NULL AND NOT PHONE RLIKE ''^[0-9]{10}$''',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU-06','DOB Not in Future','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','DATE_OF_BIRTH','Birth date must not be in future','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE DATE_OF_BIRTH > CURRENT_DATE()',0,PARSE_JSON('["validity","timeliness"]'),TRUE
UNION ALL SELECT 'CU-07','KYC Status Accepted Values','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','KYC_STATUS','Only VERIFIED, PENDING, REJECTED','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE KYC_STATUS NOT IN (''VERIFIED'',''PENDING'',''REJECTED'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU-08','Risk Category Accepted Values','BUSINESS','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS','RISK_CATEGORY','Only LOW, MEDIUM, HIGH','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS WHERE RISK_CATEGORY NOT IN (''LOW'',''MEDIUM'',''HIGH'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'CU-09','Branch FK Integrity','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','CUSTOMERS','BRANCH_ID','Branch must exist in BRANCHES','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.CUSTOMERS C LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES B ON C.BRANCH_ID=B.BRANCH_ID WHERE B.BRANCH_ID IS NULL',0,PARSE_JSON('["referential_integrity"]'),TRUE
UNION ALL SELECT 'CU-10','Row Count Check','TECHNICAL','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','CUSTOMERS',NULL,'Table must have rows','SELECT CASE WHEN COUNT(*) > 0 THEN 0 ELSE 1 END FROM BANKING_DQ_DB.RAW.CUSTOMERS',0,PARSE_JSON('["completeness"]'),TRUE;

-- ACCOUNTS rules (9 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'AC-01','Account ID Uniqueness','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_ID','No duplicate account IDs','SELECT COUNT(*) - COUNT(DISTINCT ACCOUNT_ID) FROM BANKING_DQ_DB.RAW.ACCOUNTS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'AC-02','Account ID Not Null','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_ID','PK cannot be null','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'AC-03','Balance Non-Negative','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BALANCE','Balance must be >= 0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE BALANCE < 0',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'AC-04','Account Type Accepted Values','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_TYPE','Only SAVINGS, CURRENT, LOAN','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_TYPE NOT IN (''SAVINGS'',''CURRENT'',''LOAN'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'AC-05','Account Status Accepted Values','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','ACCOUNT_STATUS','Only ACTIVE, DORMANT, CLOSED','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE ACCOUNT_STATUS NOT IN (''ACTIVE'',''DORMANT'',''CLOSED'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'AC-06','Currency Consistency','BUSINESS','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','ACCOUNTS','CURRENCY','Domestic accounts should be INR','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS WHERE CURRENCY != ''INR''',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'AC-07','Customer FK Integrity','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','CUSTOMER_ID','Customer must exist','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS A LEFT JOIN BANKING_DQ_DB.RAW.CUSTOMERS C ON A.CUSTOMER_ID=C.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL',0,PARSE_JSON('["referential_integrity"]'),TRUE
UNION ALL SELECT 'AC-08','Branch FK Integrity','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','ACCOUNTS','BRANCH_ID','Branch must exist','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.ACCOUNTS A LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES B ON A.BRANCH_ID=B.BRANCH_ID WHERE B.BRANCH_ID IS NULL',0,PARSE_JSON('["referential_integrity"]'),TRUE
UNION ALL SELECT 'AC-09','Row Count Check','TECHNICAL','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','ACCOUNTS',NULL,'Table must have rows','SELECT CASE WHEN COUNT(*) > 0 THEN 0 ELSE 1 END FROM BANKING_DQ_DB.RAW.ACCOUNTS',0,PARSE_JSON('["completeness"]'),TRUE;

-- TRANSACTIONS rules (8 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'TX-01','Transaction ID Uniqueness','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_ID','No duplicate txn IDs','SELECT COUNT(*) - COUNT(DISTINCT TRANSACTION_ID) FROM BANKING_DQ_DB.RAW.TRANSACTIONS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'TX-02','Transaction ID Not Null','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_ID','PK cannot be null','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'TX-03','Amount Positive','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','AMOUNT','Amount must be > 0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE AMOUNT <= 0',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'TX-04','Transaction Type Accepted Values','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_TYPE','Only DEBIT, CREDIT','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_TYPE NOT IN (''DEBIT'',''CREDIT'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'TX-05','Transaction Status Accepted Values','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','TRANSACTION_STATUS','Only SUCCESS, FAILED, PENDING','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE TRANSACTION_STATUS NOT IN (''SUCCESS'',''FAILED'',''PENDING'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'TX-06','Channel Accepted Values','BUSINESS','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','TRANSACTIONS','CHANNEL','Valid channels only','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS WHERE CHANNEL NOT IN (''UPI'',''NEFT'',''IMPS'',''CARD'',''ATM'',''CHEQUE'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'TX-07','Account FK Integrity','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS','ACCOUNT_ID','Account must exist','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.TRANSACTIONS T LEFT JOIN BANKING_DQ_DB.RAW.ACCOUNTS A ON T.ACCOUNT_ID=A.ACCOUNT_ID WHERE A.ACCOUNT_ID IS NULL',0,PARSE_JSON('["referential_integrity"]'),TRUE
UNION ALL SELECT 'TX-08','Row Count Check','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','TRANSACTIONS',NULL,'Table must have rows','SELECT CASE WHEN COUNT(*) > 0 THEN 0 ELSE 1 END FROM BANKING_DQ_DB.RAW.TRANSACTIONS',0,PARSE_JSON('["completeness"]'),TRUE;

-- LOAN_APPLICATIONS rules (11 rules)
INSERT INTO BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG (RULE_ID, RULE_NAME, RULE_TYPE, FREQUENCY, CRITICALITY, DB_NAME, TABLE_NM, COLUMN_NM, RULE_DESCRIPTION, RULE_SQL, THRESHOLD_VALUE, RULE_DIMENSION, IS_ACTIVE)
SELECT 'LA-01','Application ID Uniqueness','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_ID','No duplicate app IDs','SELECT COUNT(*) - COUNT(DISTINCT APPLICATION_ID) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',0,PARSE_JSON('["uniqueness"]'),TRUE
UNION ALL SELECT 'LA-02','Application ID Not Null','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_ID','PK cannot be null','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_ID IS NULL',0,PARSE_JSON('["completeness"]'),TRUE
UNION ALL SELECT 'LA-03','Requested Amount Positive','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','REQUESTED_AMOUNT','Loan request must be > 0','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE REQUESTED_AMOUNT <= 0',0,PARSE_JSON('["accuracy"]'),TRUE
UNION ALL SELECT 'LA-04','Approved LTE Requested','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPROVED_AMOUNT','Cannot approve more than requested','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPROVED_AMOUNT IS NOT NULL AND REQUESTED_AMOUNT IS NOT NULL AND APPROVED_AMOUNT > REQUESTED_AMOUNT',0,PARSE_JSON('["consistency"]'),TRUE
UNION ALL SELECT 'LA-05','Credit Score Range','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CREDIT_SCORE','Must be in range 300-850','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE CREDIT_SCORE IS NOT NULL AND (CREDIT_SCORE < 300 OR CREDIT_SCORE > 850)',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA-06','Loan Type Accepted Values','BUSINESS','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','LOAN_TYPE','Valid loan types only','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE LOAN_TYPE NOT IN (''HOME'',''CAR'',''PERSONAL'',''EDUCATION'',''BUSINESS'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA-07','Application Status Accepted','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_STATUS','Only APPROVED, PENDING, REJECTED','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_STATUS NOT IN (''APPROVED'',''PENDING'',''REJECTED'')',0,PARSE_JSON('["validity"]'),TRUE
UNION ALL SELECT 'LA-08','Application Date Not Future','BUSINESS','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','APPLICATION_DATE','Cannot apply in the future','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS WHERE APPLICATION_DATE > CURRENT_DATE()',0,PARSE_JSON('["timeliness"]'),TRUE
UNION ALL SELECT 'LA-09','Customer FK Integrity','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','CUSTOMER_ID','Customer must exist','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS L LEFT JOIN BANKING_DQ_DB.RAW.CUSTOMERS C ON L.CUSTOMER_ID=C.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL',0,PARSE_JSON('["referential_integrity"]'),TRUE
UNION ALL SELECT 'LA-10','Branch FK Integrity','TECHNICAL','ON_DEMAND','HIGH','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS','BRANCH_ID','Branch must exist','SELECT COUNT(*) FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS L LEFT JOIN BANKING_DQ_DB.RAW.BRANCHES B ON L.BRANCH_ID=B.BRANCH_ID WHERE B.BRANCH_ID IS NULL',0,PARSE_JSON('["referential_integrity"]'),TRUE
UNION ALL SELECT 'LA-11','Row Count Check','TECHNICAL','ON_DEMAND','MEDIUM','BANKING_DQ_DB.RAW','LOAN_APPLICATIONS',NULL,'Table must have rows','SELECT CASE WHEN COUNT(*) > 0 THEN 0 ELSE 1 END FROM BANKING_DQ_DB.RAW.LOAN_APPLICATIONS',0,PARSE_JSON('["completeness"]'),TRUE;

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SELECT TABLE_NM, COUNT(*) AS RULE_COUNT, 
       SUM(CASE WHEN CRITICALITY='HIGH' THEN 1 ELSE 0 END) AS HIGH_RULES,
       SUM(CASE WHEN CRITICALITY='MEDIUM' THEN 1 ELSE 0 END) AS MEDIUM_RULES
FROM BANKING_DQ_DB.DQ_MONITORING.DQ_RULE_CONFIG 
GROUP BY TABLE_NM ORDER BY TABLE_NM;
