-- System and custom DMF creation and attachment scripts for BANKING_DQ_DB.RAW tables
-- Co-authored with CoCo

-- ============================================================================
-- STEP 3: CREATE AND ATTACH DATA QUALITY RULES (DMFs)
-- ============================================================================
-- Note: SNOWFLAKE.CORE.FRESHNESS is not available in this account.
-- Using: NULL_COUNT, DUPLICATE_COUNT, ROW_COUNT (system) + 8 custom DMFs.
-- ============================================================================

USE DATABASE BANKING_DQ_DB;
USE SCHEMA RAW;

-- ============================================================================
-- PART A: CREATE CUSTOM DATA METRIC FUNCTIONS
-- ============================================================================

-- A1: Email format validation (returns count of invalid emails)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_EMAIL_FORMAT_CHECK(
    ARG_T TABLE(ARG_C TEXT)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND NOT ARG_C RLIKE '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
$$;

-- A2: Phone format validation (returns count of invalid phone numbers, expected 10 digits)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_PHONE_FORMAT_CHECK(
    ARG_T TABLE(ARG_C TEXT)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND NOT ARG_C RLIKE '^[0-9]{10}$'
$$;

-- A3: IFSC code format validation (expected: 4 uppercase letters + 7 digits)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_IFSC_FORMAT_CHECK(
    ARG_T TABLE(ARG_C TEXT)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND NOT ARG_C RLIKE '^[A-Z]{4}[0-9]{7}$'
$$;

-- A4: Positive amount check (returns count of rows with amount <= 0)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_POSITIVE_AMOUNT_CHECK(
    ARG_T TABLE(ARG_C NUMBER)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND ARG_C <= 0
$$;

-- A5: Non-negative balance check (returns count of rows with negative balance)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_NON_NEGATIVE_BALANCE_CHECK(
    ARG_T TABLE(ARG_C NUMBER)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND ARG_C < 0
$$;

-- A6: Credit score range check (valid range: 300-850)
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_CREDIT_SCORE_RANGE_CHECK(
    ARG_T TABLE(ARG_C NUMBER)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C IS NOT NULL AND (ARG_C < 300 OR ARG_C > 850)
$$;

-- A7: Future date check (returns count of dates after 2026-07-11)
-- Note: CURRENT_DATE() not allowed in DMFs; using fixed boundary date
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_FUTURE_DATE_CHECK(
    ARG_T TABLE(ARG_C DATE)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_C > '2026-07-11'::DATE
$$;

-- A8: Approved amount must not exceed requested amount
CREATE OR REPLACE DATA METRIC FUNCTION BANKING_DQ_DB.RAW.DQ_APPROVED_LTE_REQUESTED(
    ARG_T TABLE(ARG_APPROVED NUMBER, ARG_REQUESTED NUMBER)
)
RETURNS NUMBER
AS
$$
SELECT COUNT(*) FROM ARG_T WHERE ARG_APPROVED IS NOT NULL AND ARG_REQUESTED IS NOT NULL AND ARG_APPROVED > ARG_REQUESTED
$$;

-- ============================================================================
-- PART B: ATTACH DMFs TO TABLES
-- ============================================================================

-- B1: BRANCHES (7 DMFs)
ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES
  ADD DATA METRIC FUNCTION
    SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (BRANCH_NAME),
    SNOWFLAKE.CORE.NULL_COUNT ON (IFSC_CODE),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (BRANCH_ID),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (IFSC_CODE),
    SNOWFLAKE.CORE.ROW_COUNT ON (),
    BANKING_DQ_DB.RAW.DQ_IFSC_FORMAT_CHECK ON (IFSC_CODE);

-- B2: CUSTOMERS (9 DMFs)
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS
  ADD DATA METRIC FUNCTION
    SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (FIRST_NAME),
    SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (EMAIL),
    SNOWFLAKE.CORE.ROW_COUNT ON (),
    BANKING_DQ_DB.RAW.DQ_EMAIL_FORMAT_CHECK ON (EMAIL),
    BANKING_DQ_DB.RAW.DQ_PHONE_FORMAT_CHECK ON (PHONE),
    BANKING_DQ_DB.RAW.DQ_FUTURE_DATE_CHECK ON (DATE_OF_BIRTH);

-- B3: ACCOUNTS (6 DMFs)
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS
  ADD DATA METRIC FUNCTION
    SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (BALANCE),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ACCOUNT_ID),
    SNOWFLAKE.CORE.ROW_COUNT ON (),
    BANKING_DQ_DB.RAW.DQ_NON_NEGATIVE_BALANCE_CHECK ON (BALANCE);

-- B4: TRANSACTIONS (6 DMFs)
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS
  ADD DATA METRIC FUNCTION
    SNOWFLAKE.CORE.NULL_COUNT ON (TRANSACTION_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (ACCOUNT_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (AMOUNT),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TRANSACTION_ID),
    SNOWFLAKE.CORE.ROW_COUNT ON (),
    BANKING_DQ_DB.RAW.DQ_POSITIVE_AMOUNT_CHECK ON (AMOUNT);

-- B5: LOAN_APPLICATIONS (9 DMFs)
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS
  ADD DATA METRIC FUNCTION
    SNOWFLAKE.CORE.NULL_COUNT ON (APPLICATION_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID),
    SNOWFLAKE.CORE.NULL_COUNT ON (REQUESTED_AMOUNT),
    SNOWFLAKE.CORE.DUPLICATE_COUNT ON (APPLICATION_ID),
    SNOWFLAKE.CORE.ROW_COUNT ON (),
    BANKING_DQ_DB.RAW.DQ_POSITIVE_AMOUNT_CHECK ON (REQUESTED_AMOUNT),
    BANKING_DQ_DB.RAW.DQ_CREDIT_SCORE_RANGE_CHECK ON (CREDIT_SCORE),
    BANKING_DQ_DB.RAW.DQ_FUTURE_DATE_CHECK ON (APPLICATION_DATE),
    BANKING_DQ_DB.RAW.DQ_APPROVED_LTE_REQUESTED ON (APPROVED_AMOUNT, REQUESTED_AMOUNT);

-- ============================================================================
-- PART C: SET DMF SCHEDULE
-- ============================================================================

ALTER TABLE BANKING_DQ_DB.RAW.BRANCHES SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.CUSTOMERS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.ACCOUNTS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.TRANSACTIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER TABLE BANKING_DQ_DB.RAW.LOAN_APPLICATIONS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- ============================================================================
-- SUMMARY
-- ============================================================================
-- Total Custom DMFs Created: 8
-- Total DMF Attachments:
--   BRANCHES:          7 (3 NULL_COUNT, 2 DUPLICATE_COUNT, 1 ROW_COUNT, 1 IFSC format)
--   CUSTOMERS:         9 (3 NULL_COUNT, 2 DUPLICATE_COUNT, 1 ROW_COUNT, 3 custom)
--   ACCOUNTS:          6 (3 NULL_COUNT, 1 DUPLICATE_COUNT, 1 ROW_COUNT, 1 custom)
--   TRANSACTIONS:      6 (3 NULL_COUNT, 1 DUPLICATE_COUNT, 1 ROW_COUNT, 1 custom)
--   LOAN_APPLICATIONS: 9 (3 NULL_COUNT, 1 DUPLICATE_COUNT, 1 ROW_COUNT, 4 custom)
-- Grand Total: 37 DMF associations across 5 tables
-- Schedule: TRIGGER_ON_CHANGES (runs when data is modified)
-- ============================================================================
